import { AlertTriangle, Brush, CheckCircle2, ClipboardCheck, DollarSign, FileText, Megaphone, Search, ShieldCheck, Store, Target } from "lucide-react";
import { SectionHeader } from "@/components/SectionHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { assetRequests, complianceGates, etsyConcepts, factoryOfficers, fiverrConcepts, incomeFactoryGoal, marketOpportunities, offerDrafts, publishingQueue, revenueExperiments, type AssetRequest, type ComplianceGate, type EtsyConcept, type FiverrConcept, type MarketOpportunity, type OfferDraft, type PublishingItem, type RevenueExperiment } from "@/data/incomeFactory";

export function IncomeDivision() {
  return (
    <div className="space-y-7">
      <section className="relative overflow-hidden rounded-lg border border-emerald-300/25 bg-card/80 p-6 shadow-[0_0_80px_rgba(52,211,153,0.12)] md:p-8">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(52,211,153,0.18),transparent_26rem),linear-gradient(rgba(52,211,153,0.06)_1px,transparent_1px),linear-gradient(90deg,rgba(34,211,238,0.04)_1px,transparent_1px)] bg-[size:auto,42px_42px,42px_42px]" />
        <div className="relative grid gap-6 lg:grid-cols-[1.1fr_0.9fr] lg:items-end">
          <div className="space-y-4"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-300/30 bg-emerald-300/10 px-3 py-1 text-xs font-medium uppercase tracking-[0.16em] text-emerald-200"><DollarSign className="h-3.5 w-3.5" /> v0.7 Assisted Factory</div><div className="space-y-3"><h1 className="font-display text-4xl font-semibold leading-tight md:text-6xl">Income Division</h1><p className="max-w-3xl text-base leading-7 text-muted-foreground md:text-lg">Assisted revenue factory foundation for original offers, manual publishing, evidence tracking, and compliance gates. No account automation, no scraping violations, no auto-publishing, no auto-DMs, no ad spend.</p></div></div>
          <Card className="border-red-300/30 bg-red-950/15"><CardHeader className="flex-row items-start gap-3"><ShieldCheck className="mt-1 h-5 w-5 text-red-200" /><div><CardTitle className="text-red-100">Manual Gate Active</CardTitle><CardDescription>{incomeFactoryGoal.safety}</CardDescription></div></CardHeader></Card>
        </div>
      </section>

      <section className="space-y-4"><SectionHeader eyebrow="Factory Doctrine" title={incomeFactoryGoal.goal} description={incomeFactoryGoal.currentPhase} /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{incomeFactoryGoal.doctrine.map((item) => <div key={item} className="rounded-md border border-emerald-300/20 bg-emerald-300/10 p-3 text-sm leading-6 text-emerald-100">{item}</div>)}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{factoryOfficers.map((officer) => <div key={officer} className="rounded-md border border-cyan-300/20 bg-cyan-300/10 p-3 text-sm font-medium text-cyan-100">{officer}</div>)}</div></section>

      <section className="space-y-4"><SectionHeader eyebrow="Market Lab" title="Product opportunity queue" description="Research demand patterns manually. Study markets without copying listings or violating platform terms." /><div className="grid gap-4 lg:grid-cols-3">{marketOpportunities.map((item) => <MarketCard key={item.id} item={item} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Offer Builder" title="Original differentiated offers" description="Draft the offer before asset creation or publishing. Approval remains manual." /><div className="grid gap-4 lg:grid-cols-2">{offerDrafts.map((item) => <OfferCard key={item.id} item={item} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Asset Factory" title="Creative work requests" description="Requests can be assigned to Design Forge, Copy Room, Revenue Architect, Publishing Room, or Sentinel for review." /><div className="grid gap-4 lg:grid-cols-3">{assetRequests.map((item) => <AssetCard key={item.id} item={item} />)}</div></section>
      <section className="grid gap-4 xl:grid-cols-2"><div className="space-y-4"><SectionHeader eyebrow="Fiverr Room" title="Gig concepts" description="Productized service drafts only. Human review and manual publishing required." />{fiverrConcepts.map((item) => <FiverrCard key={item.id} item={item} />)}</div><div className="space-y-4"><SectionHeader eyebrow="Etsy Room" title="Listing concepts" description="Listing drafts only. SEO, mockups, files, and checklist remain manual." />{etsyConcepts.map((item) => <EtsyCard key={item.id} item={item} />)}</div></section>
      <section className="grid gap-4 xl:grid-cols-2"><div className="space-y-4"><SectionHeader eyebrow="Publishing Room" title="Prepared items only" description="Nothing publishes itself. Approval and manual action are required." />{publishingQueue.map((item) => <PublishingCard key={item.id} item={item} />)}</div><div className="space-y-4"><SectionHeader eyebrow="Revenue War Room" title="Experiments and decisions" description="Track views, clicks, orders, revenue, and kill/iterate/scale decisions only when real data exists." />{revenueExperiments.map((item) => <RevenueCard key={item.id} item={item} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Compliance Sentinel" title="Human approval gate" description="Trademark, copyright, platform terms, and human approval checks are required before publishing." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{complianceGates.map((item) => <ComplianceCard key={item.id} item={item} />)}</div></section>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string | null }) { return <div className="rounded-md border border-border/70 bg-background/50 p-3"><p className="mb-1 text-xs uppercase tracking-[0.14em] text-muted-foreground">{label}</p><p className="text-sm leading-6 text-foreground/90">{value ?? "No real data yet"}</p></div>; }
function MarketCard({ item }: { item: MarketOpportunity }) { return <Card className="border-emerald-300/25"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Search className="h-5 w-5 text-emerald-200" />{item.title}</CardTitle><CardDescription>{item.platform}</CardDescription></CardHeader><CardContent className="space-y-3"><StatusBadge label={item.status} tone="manual" /><Field label="Demand evidence" value={item.demandEvidence} /><Field label="Competition notes" value={item.competitionNotes} /></CardContent></Card>; }
function OfferCard({ item }: { item: OfferDraft }) { return <Card className="border-cyan-300/25"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Target className="h-5 w-5 text-cyan-200" />{item.offerTitle}</CardTitle><CardDescription>{item.targetCustomer}</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Field label="Pain point" value={item.painPoint} /><Field label="Deliverable" value={item.deliverable} /><Field label="Price" value={item.price} /><Field label="Differentiation" value={item.differentiation} /><Field label="Approval" value={item.approvalStatus} /></CardContent></Card>; }
function AssetCard({ item }: { item: AssetRequest }) { return <Card className="border-purple-300/25"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Brush className="h-5 w-5 text-purple-200" />{item.productType}</CardTitle><CardDescription>{item.assignedOfficer}</CardDescription></CardHeader><CardContent className="space-y-3"><StatusBadge label={item.status} tone="beta" /><Field label="Asset request" value={item.assetRequest} /></CardContent></Card>; }
function FiverrCard({ item }: { item: FiverrConcept }) { return <Card className="border-blue-300/25"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><FileText className="h-5 w-5 text-blue-200" />{item.gigConcept}</CardTitle><CardDescription>Fiverr Room</CardDescription></CardHeader><CardContent className="space-y-3"><Field label="Package tiers" value={item.packageTiers} /><Field label="Delivery scope" value={item.deliveryScope} /><Field label="FAQ" value={item.faq} /><Field label="Buyer requirements" value={item.buyerRequirements} /><Checklist items={item.manualPublishChecklist} /></CardContent></Card>; }
function EtsyCard({ item }: { item: EtsyConcept }) { return <Card className="border-amber-300/25"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Store className="h-5 w-5 text-amber-200" />{item.listingConcept}</CardTitle><CardDescription>{item.seoTitle}</CardDescription></CardHeader><CardContent className="space-y-3"><Field label="Tags" value={item.tags.join(" / ")} /><Field label="Mockup status" value={item.mockupStatus} /><Field label="Digital file status" value={item.digitalFileStatus} /><Checklist items={item.manualPublishChecklist} /></CardContent></Card>; }
function PublishingCard({ item }: { item: PublishingItem }) { return <Card className="border-fuchsia-300/25"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Megaphone className="h-5 w-5 text-fuchsia-200" />{item.item}</CardTitle><CardDescription>{item.channel}</CardDescription></CardHeader><CardContent className="space-y-3"><StatusBadge label={item.approvalRequired ? "Approval Required" : "Approved"} tone="manual" /><Field label="Schedule placeholder" value={item.schedulePlaceholder} /><Field label="Manual action" value={item.manualActionRequired} /></CardContent></Card>; }
function RevenueCard({ item }: { item: RevenueExperiment }) { return <Card className="border-emerald-300/25"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><DollarSign className="h-5 w-5 text-emerald-200" />{item.experiment}</CardTitle><CardDescription>Revenue War Room</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Field label="Views" value={item.views} /><Field label="Clicks" value={item.clicks} /><Field label="Orders" value={item.orders} /><Field label="Revenue" value={item.revenue} /><Field label="Decision" value={item.decision} /><Field label="Evidence" value={item.evidenceNote} /></CardContent></Card>; }
function ComplianceCard({ item }: { item: ComplianceGate }) { return <Card className="border-red-300/25"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><AlertTriangle className="h-5 w-5 text-red-200" />{item.check}</CardTitle><CardDescription>{item.owner}</CardDescription></CardHeader><CardContent className="space-y-3"><StatusBadge label={item.status} tone="danger" /><Field label="Note" value={item.note} /></CardContent></Card>; }
function Checklist({ items }: { items: string[] }) { return <div className="rounded-md border border-border/70 bg-background/50 p-3"><p className="mb-2 flex items-center gap-2 text-xs uppercase tracking-[0.14em] text-muted-foreground"><ClipboardCheck className="h-3.5 w-3.5" />Manual checklist</p><div className="space-y-2">{items.map((item) => <div key={item} className="flex gap-2 text-sm text-foreground/90"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-200" />{item}</div>)}</div></div>; }
