import { GitBranch, RadioTower, Route, ShieldCheck } from "lucide-react";
import { SectionHeader } from "@/components/SectionHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { researchMissionLifecycle, researchPlatforms, researchRouterMetrics, researchRouterSummary, routedResearchMissions, type ResearchMissionLifecycle, type ResearchMissionPriority, type ResearchPlatformStatus } from "@/data/researchRouter";
import { missionRecordFields, obsidianVaultMetrics, obsidianVaultSummary, obsidianVaultZones } from "@/data/obsidianVault";

const platformTone: Record<ResearchPlatformStatus, "success" | "manual" | "beta" | "muted"> = { Available: "success", Offline: "muted", Reserved: "manual", Future: "beta" };
const lifecycleTone: Record<ResearchMissionLifecycle, "success" | "manual" | "beta" | "danger" | "muted"> = { Created: "beta", Assigned: "manual", Researching: "manual", Completed: "success", Reviewed: "success", Archived: "muted", Rejected: "danger" };
const priorityTone: Record<ResearchMissionPriority, "danger" | "manual" | "beta" | "success"> = { P0: "danger", P1: "manual", P2: "beta", P3: "success" };

export function ResearchRouter() {
  return (
    <div className="space-y-7">
      <section className="relative overflow-hidden rounded-lg border border-purple-300/30 bg-card/85 p-6 shadow-[0_0_90px_rgba(168,85,247,0.14)] md:p-8">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_18%_18%,rgba(168,85,247,0.18),transparent_24rem),linear-gradient(rgba(34,211,238,0.06)_1px,transparent_1px),linear-gradient(90deg,rgba(251,191,36,0.04)_1px,transparent_1px)] bg-[size:auto,38px_38px,38px_38px]" />
        <div className="relative grid gap-6 xl:grid-cols-[1.15fr_0.85fr] xl:items-end">
          <div className="space-y-5"><div className="inline-flex items-center gap-2 rounded-full border border-purple-300/35 bg-purple-300/10 px-3 py-1 text-xs font-medium uppercase tracking-[0.16em] text-purple-100"><Route className="h-3.5 w-3.5" /> {researchRouterSummary.version} Research Router</div><div className="space-y-3"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-purple-200">Assignment layer</p><h1 className="font-display text-4xl font-semibold leading-tight md:text-6xl">Research Router</h1><p className="max-w-3xl text-base leading-7 text-muted-foreground md:text-lg">{researchRouterSummary.mission}</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Platforms" value={String(researchRouterMetrics.platforms)} /><Metric label="Available" value={String(researchRouterMetrics.availablePlatforms)} /><Metric label="Missions" value={String(researchRouterMetrics.missions)} /><Metric label="Assigned" value={String(researchRouterMetrics.assigned)} /><Metric label="External Routes" value="0" /></div></div>
          <Card className="border-red-300/30 bg-red-950/15"><CardHeader className="flex-row items-start gap-3"><ShieldCheck className="mt-1 h-5 w-5 text-red-200" /><div><CardTitle className="text-red-100">Typed router only</CardTitle><CardDescription>{researchRouterSummary.safety}</CardDescription></div></CardHeader></Card>
        </div>
      </section>

      <section className="space-y-4"><SectionHeader eyebrow="Lifecycle" title="Mission routing states" description="Research missions move through review states. No state triggers an external action in v3.0." /><div className="grid gap-3 md:grid-cols-4 xl:grid-cols-7">{researchMissionLifecycle.map((stage) => <div key={stage} className="rounded-md border border-purple-300/20 bg-purple-300/10 p-3 text-center"><StatusBadge label={stage} tone={lifecycleTone[stage]} /></div>)}</div></section>

      <section className="space-y-4"><SectionHeader eyebrow="Platforms" title="First available AI platform" description={researchRouterSummary.doctrine} /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{researchPlatforms.map((platform) => <Card key={platform.id} className="border-cyan-300/25 bg-card/80"><CardHeader><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-200">{platform.id}</p><CardTitle className="mt-2 text-xl">{platform.platform}</CardTitle></div><StatusBadge label={platform.status} tone={platformTone[platform.status]} /></div><CardDescription>{platform.currentBoundary}</CardDescription></CardHeader><CardContent><List title="Best For" items={platform.bestFor} /></CardContent></Card>)}</div></section>

      <section className="space-y-4"><SectionHeader eyebrow="Mission Queue" title="Routed research missions" description="The queue records assignment intent and knowledge destination without calling any external provider." /><div className="grid gap-4 xl:grid-cols-2">{routedResearchMissions.map((mission) => <Card key={mission.id} className="border-amber-300/25 bg-card/80"><CardHeader><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-amber-200">{mission.id} / {mission.division}</p><CardTitle className="mt-2 text-xl">{mission.title}</CardTitle></div><div className="flex flex-wrap gap-2"><StatusBadge label={mission.lifecycle} tone={lifecycleTone[mission.lifecycle]} /><StatusBadge label={mission.priority} tone={priorityTone[mission.priority]} /></div></div><CardDescription>{mission.objective}</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Info label="Assigned Platform" value={mission.assignedPlatform} /><Info label="Expected Output" value={mission.expectedOutput} /><Info label="Knowledge Destination" value={mission.knowledgeDestination} /><Info label="Approval" value={mission.approvalRequirement} /></CardContent></Card>)}</div></section>

      <section className="space-y-4"><SectionHeader eyebrow="Obsidian" title="Canonical vault memory" description={obsidianVaultSummary.doctrine} /><Card className="border-emerald-300/30 bg-emerald-950/15"><CardHeader><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-200">{obsidianVaultSummary.root}</p><CardTitle className="mt-2 text-2xl text-emerald-100">Mission record schema</CardTitle></div><GitBranch className="h-5 w-5 text-emerald-200" /></div><CardDescription>{obsidianVaultSummary.safety}</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><Metric label="Vault Zones" value={String(obsidianVaultMetrics.zones)} /><Metric label="Canonical" value={String(obsidianVaultMetrics.canonicalZones)} /><Metric label="Record Fields" value={String(obsidianVaultMetrics.missionRecordFields)} /><Metric label="Sync Automations" value="0" /></CardContent></Card><div className="grid gap-4 xl:grid-cols-[0.9fr_1.1fr]"><Card className="border-emerald-300/25 bg-card/80"><CardHeader><CardTitle>Vault zones</CardTitle><CardDescription>Top-level durable memory structure.</CardDescription></CardHeader><CardContent className="space-y-2">{obsidianVaultZones.map((zone) => <Info key={zone.id} label={zone.path} value={zone.purpose} />)}</CardContent></Card><Card className="border-cyan-300/25 bg-card/80"><CardHeader><CardTitle>Mission record fields</CardTitle><CardDescription>Every research mission record should preserve these fields.</CardDescription></CardHeader><CardContent className="grid gap-2 md:grid-cols-2">{missionRecordFields.map((field) => <Info key={field.field} label={field.required ? field.field + " / Required" : field.field} value={field.purpose} />)}</CardContent></Card></div></section>
    </div>
  );
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-md border border-border/70 bg-background/50 p-3"><p className="mb-1 text-xs uppercase tracking-[0.14em] text-muted-foreground">{label}</p><p className="text-sm leading-6 text-foreground/90">{value}</p></div>; }
function List({ title, items }: { title: string; items: string[] }) { return <div className="rounded-md border border-border/70 bg-background/50 p-3"><p className="mb-2 text-xs uppercase tracking-[0.14em] text-muted-foreground">{title}</p><div className="space-y-2">{items.map((item) => <p key={item} className="rounded-md border border-purple-300/15 bg-purple-300/10 p-2 text-sm leading-5 text-purple-100">{item}</p>)}</div></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-md border border-purple-300/20 bg-background/50 p-3"><p className="mb-1 text-xs uppercase tracking-[0.14em] text-muted-foreground">{label}</p><p className="text-sm font-medium leading-6 text-foreground/90">{value}</p></div>; }
