import { BarChart3, CheckCircle2, CircleDollarSign, FileText, Radar, RotateCcw, ShieldCheck, Trophy, XCircle } from "lucide-react";
import { SectionHeader } from "@/components/SectionHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { approvalDoctrine, approvalQueue, decisionRecords, type ApprovalRequest, type ApprovalRisk, type ApprovalStatus, type DecisionRecord } from "@/data/approvalSystem";
import { hermesAgentProfiles } from "@/data/hermesAgents";
import { revenueArchitectBoard, revenueArchitectMission, type RevenueArchitectBoardItem, type RevenueArchitectBoardStatus } from "@/data/revenueArchitect";
import { experimentTracker, hallOfWins, opportunityPipeline, opportunityRadar, pipelineStages, playbookLibrary, revenueDashboardMetrics, revenueIntelligenceDoctrine, revenueScores, marketScannerCandidates, type Confidence, type FactorValue, type PipelineStage, type RadarStatus } from "@/data/revenueIntelligence";
import { senateDoctrine, senateRecommendations, type SenateConfidence } from "@/data/senate";
import { scoutDoctrine, scoutOfficers } from "@/data/scoutOfficers";

const confidenceTone: Record<Confidence | SenateConfidence, "success" | "manual" | "beta" | "muted"> = { Unknown: "muted", Low: "beta", Medium: "manual", High: "success" };
const radarTone: Record<RadarStatus, "success" | "manual" | "beta" | "muted" | "danger"> = { Research: "manual", Watching: "beta", Active: "success", Rejected: "danger", Validated: "success" };
const stageTone: Record<PipelineStage, "success" | "manual" | "beta" | "muted"> = { Research: "manual", Validate: "beta", Prototype: "beta", Publish: "manual", Scale: "success", Systematize: "success" };
const approvalStatusTone: Record<ApprovalStatus, "success" | "manual" | "danger" | "beta"> = { "Awaiting Commander": "manual", Approved: "success", Declined: "danger", "Revision Requested": "beta" };
const approvalRiskTone: Record<ApprovalRisk, "success" | "manual" | "danger"> = { LOW: "success", MEDIUM: "manual", HIGH: "danger" };

export function RevenueIntelligence() {
  return (
    <div className="space-y-7">
      <section className="relative overflow-hidden rounded-lg border border-emerald-300/25 bg-card/80 p-6 shadow-[0_0_80px_rgba(52,211,153,0.12)] md:p-8">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(52,211,153,0.18),transparent_26rem),linear-gradient(rgba(52,211,153,0.06)_1px,transparent_1px),linear-gradient(90deg,rgba(34,211,238,0.04)_1px,transparent_1px)] bg-[size:auto,42px_42px,42px_42px]" />
        <div className="relative grid gap-6 lg:grid-cols-[1.1fr_0.9fr] lg:items-end">
          <div className="space-y-4"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-300/30 bg-emerald-300/10 px-3 py-1 text-xs font-medium uppercase tracking-[0.16em] text-emerald-200"><CircleDollarSign className="h-3.5 w-3.5" /> v0.9 Revenue Intelligence</div><div className="space-y-3"><h1 className="font-display text-4xl font-semibold leading-tight md:text-6xl">Revenue Intelligence</h1><p className="max-w-3xl text-base leading-7 text-muted-foreground md:text-lg">Read-only intelligence for identifying, validating, prioritizing, and systematizing profitable digital business workflows. Unknown values stay Unknown.</p></div></div>
          <Card className="border-red-300/30 bg-red-950/15"><CardHeader className="flex-row items-start gap-3"><ShieldCheck className="mt-1 h-5 w-5 text-red-200" /><div><CardTitle className="text-red-100">Read-Only Intelligence</CardTitle><CardDescription>No autonomous publishing, marketplace interaction, ToS-violating scraping, account automation, purchasing, customer messaging, or fabricated metrics.</CardDescription></div></CardHeader></Card>
        </div>
      </section>

      <section className="space-y-4"><SectionHeader eyebrow="Doctrine" title="Evidence-first revenue system" description="The engine prioritizes evidence quality over activity theater." /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6">{revenueIntelligenceDoctrine.map((item) => <div key={item} className="rounded-md border border-emerald-300/20 bg-emerald-300/10 p-3 text-sm leading-6 text-emerald-100">{item}</div>)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Scout Evidence Layer" title="Opportunity discovery officers" description="Market Scout, Demand Scout, and Risk Scout prepare research reports for Revenue Architect. No publishing, messaging, spending, or platform-rule scraping." /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{scoutDoctrine.map((item) => <div key={item} className="rounded-md border border-cyan-300/20 bg-cyan-300/10 p-3 text-sm leading-6 text-cyan-100">{item}</div>)}</div><div className="grid gap-4 md:grid-cols-3">{scoutOfficers.map((scout) => <Card key={scout.id} className="border-cyan-300/25 bg-card/80"><CardHeader><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-md border border-cyan-300/30 bg-cyan-300/10 text-2xl">{scout.emoji}</span><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-200">Reports to {scout.reportsTo}</p><CardTitle className="mt-1 text-lg">{scout.name}</CardTitle></div></div><StatusBadge label={scout.status} tone="beta" /></div><CardDescription>{scout.mission}</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><Info label="Watches" value={scout.watches.join(" / ")} /><Info label="Evidence Rule" value={scout.evidenceRules.join(" / ")} /></CardContent></Card>)}</div></section>

      <section className="space-y-4"><SectionHeader eyebrow="Revenue Architect" title="Operation First Revenue board" description="A manual operating board for the first revenue campaign: priorities, queues, evidence, experiments, approvals, and wins without fake metrics or autonomous marketplace action." /><Card className="border-emerald-300/35 bg-emerald-950/15"><CardHeader><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-200">{revenueArchitectMission.officer}</p><CardTitle className="mt-2 text-2xl text-emerald-100">{revenueArchitectMission.objective}</CardTitle></div><StatusBadge label="Manual Only" tone="manual" /></div><CardDescription>{revenueArchitectMission.mission}</CardDescription></CardHeader><CardContent className="grid gap-3 lg:grid-cols-2"><Info label="Doctrine" value={revenueArchitectMission.doctrine} /><Info label="Safety" value={revenueArchitectMission.safety} /></CardContent></Card><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{revenueArchitectBoard.map((item) => <RevenueArchitectCard key={item.id} item={item} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Approval System" title="First-class approval queue" description="Everything irreversible flows through this queue. Current buttons are review placeholders only; no backend, persistence, or external action is connected." /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{approvalDoctrine.map((item) => <div key={item} className="rounded-md border border-amber-300/20 bg-amber-300/10 p-3 text-sm leading-6 text-amber-100">{item}</div>)}</div><div className="grid gap-4 xl:grid-cols-2">{approvalQueue.map((request) => <ApprovalCard key={request.id} request={request} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Decision Records" title="Why decisions were made" description="Mission Records answer what happened. Decision Records answer why THE GRID chose a direction." /><div className="grid gap-4 xl:grid-cols-2">{decisionRecords.map((record) => <DecisionRecordCard key={record.id} record={record} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Market Scanner" title="Opportunity candidates" description="Tracks opportunity, platform, category, demand, competition, margin, operator fit, recurring potential, automation potential, confidence, and status." /><div className="grid gap-4 xl:grid-cols-3">{marketScannerCandidates.map((candidate) => <MarketScannerCard key={candidate.id} candidate={candidate} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Opportunity Pipeline" title="Stage gates" description="Research, Validate, Prototype, Publish, Scale, and Systematize remain explicit gates." /><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6">{pipelineStages.map((stage) => <div key={stage} className="rounded-md border border-border/70 bg-background/50 p-3 text-center"><StatusBadge label={stage} tone={stageTone[stage]} /></div>)}</div><div className="grid gap-4 lg:grid-cols-3">{opportunityPipeline.map((item) => <PipelineCard key={item.id} item={item} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Revenue Score" title="Composite score readiness" description="Scores stay Unknown until all score inputs have evidence." /><div className="grid gap-4 lg:grid-cols-3">{revenueScores.map((score) => <ScoreCard key={score.id} score={score} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Experiment Tracker" title="Hypothesis, evidence, decision" description="Each experiment needs evidence before scale, kill, or retry decisions become meaningful." /><div className="grid gap-4 lg:grid-cols-3">{experimentTracker.map((item) => <ExperimentCard key={item.id} item={item} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Revenue Dashboard" title="Unknown until measured" description="Products, published count, revenue, profit, time invested, and ROI are never fabricated." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-6">{revenueDashboardMetrics.map((metric) => <MetricCard key={metric.label} label={metric.label} value={metric.value} note={metric.note} />)}</div></section>
      <section className="grid gap-4 xl:grid-cols-[1fr_1fr]"><div className="space-y-4"><SectionHeader eyebrow="Hall of Wins" title="Validated milestones only" description="Milestones are visible, but none are claimed until evidence exists." />{hallOfWins.map((win) => <WinCard key={win.id} win={win} />)}</div><div className="space-y-4"><SectionHeader eyebrow="Opportunity Radar" title="Research, Watching, Active, Rejected, Validated" description="Radar status is a review state, not a live-marketplace signal." />{opportunityRadar.map((item) => <RadarCard key={item.id} item={item} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Playbook Library" title="Successful workflows only after proof" description="Draft workflows can exist, but only evidence-backed workflows become validated playbooks." /><div className="grid gap-4 lg:grid-cols-2">{playbookLibrary.map((entry) => <PlaybookCard key={entry.id} entry={entry} />)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="Hermes Support" title="Revenue specialists prepared for future workflows" description="Revenue Architect, Design Forge, Copy Room, Sentinel, and ZENITH are represented as read-only profiles with approval gates before any live integration exists." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{hermesAgentProfiles.map((profile) => <Card key={profile.id} className="border-cyan-300/20"><CardHeader><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-md border border-cyan-300/30 bg-cyan-300/10 text-xl">{profile.emoji}</span><div><CardTitle className="text-base">{profile.name}</CardTitle><CardDescription>{profile.allowedAutonomyLevel}</CardDescription></div></div></CardHeader><CardContent><Info label="Gate" value={profile.approvalGates[0]} /></CardContent></Card>)}</div></section>
      <section className="space-y-4"><SectionHeader eyebrow="The Senate" title="Decision support" description={senateDoctrine} /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{senateRecommendations.map((item) => <SenateCard key={item.id} item={item} />)}</div></section>
    </div>
  );
}

function ApprovalCard({ request }: { request: ApprovalRequest }) {
  return <Card className="border-amber-300/30 bg-card/80"><CardHeader><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-amber-200">{request.id} / {request.requester}</p><CardTitle className="mt-2 text-xl">{request.title}</CardTitle></div><StatusBadge label={request.status} tone={approvalStatusTone[request.status]} /></div><CardDescription>{request.mission}</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-md border border-border/70 bg-background/50 p-3"><p className="mb-2 text-xs uppercase tracking-[0.14em] text-muted-foreground">Risk</p><StatusBadge label={request.risk} tone={approvalRiskTone[request.risk]} /></div><Info label="Cost" value={request.cost} /></div><Info label="Summary" value={request.summary} /><Info label="Evidence" value={request.evidence} /><Info label="Boundary" value={request.irreversibleBoundary} /><Info label="Decision Requested" value={request.requestedDecision} /><div className="flex flex-wrap gap-2 border-t border-border/70 pt-3"><Button size="sm" disabled><CheckCircle2 className="h-4 w-4" />Approve</Button><Button size="sm" variant="outline" disabled><XCircle className="h-4 w-4" />Decline</Button><Button size="sm" variant="outline" disabled><RotateCcw className="h-4 w-4" />Request Revision</Button></div></CardContent></Card>;
}

function DecisionRecordCard({ record }: { record: DecisionRecord }) {
  return <Card className="border-blue-300/25 bg-card/80"><CardHeader><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-blue-200">{record.id}</p><CardTitle className="mt-2 text-xl">{record.decision}</CardTitle></div><FileText className="h-5 w-5 text-blue-200" /></div><CardDescription>Approved by {record.approvedBy} / {record.date}</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><Info label="Reason" value={record.reason} /><Info label="Evidence" value={record.evidence} /><Info label="Outcome" value={record.outcome} /></CardContent></Card>;
}

const boardTone: Record<RevenueArchitectBoardStatus, "success" | "manual" | "beta" | "muted"> = { Active: "success", Planned: "beta", "Manual Only": "manual", "Pending Evidence": "muted", Parked: "muted", Validated: "success" };

function RevenueArchitectCard({ item }: { item: RevenueArchitectBoardItem }) {
  return <Card className="border-emerald-300/20 bg-card/80"><CardHeader><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-200">Revenue Architect</p><CardTitle className="mt-2 text-lg">{item.name}</CardTitle></div><StatusBadge label={item.currentState} tone={boardTone[item.currentState]} /></div><CardDescription>{item.purpose}</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><Info label="Evidence Rule" value={item.evidenceRule} /><Info label="Approval Gate" value={item.approvalGate} /></CardContent></Card>;
}

function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-md border border-border/70 bg-background/50 p-3"><p className="mb-1 text-xs uppercase tracking-[0.14em] text-muted-foreground">{label}</p><p className="text-sm leading-6 text-foreground/90">{value}</p></div>; }
function Factor({ label, value }: { label: string; value: FactorValue }) { return <Info label={label} value={value} />; }
function MarketScannerCard({ candidate }: { candidate: typeof marketScannerCandidates[number] }) { return <Card className="border-emerald-300/25"><CardHeader><div className="flex items-start justify-between gap-3"><CardTitle className="text-lg">{candidate.opportunity}</CardTitle><StatusBadge label={candidate.status} tone={radarTone[candidate.status]} /></div><CardDescription>{candidate.platform} / {candidate.category}</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Factor label="Demand" value={candidate.demand} /><Factor label="Competition" value={candidate.competition} /><Factor label="Margin" value={candidate.margin} /><Factor label="Operator Fit" value={candidate.operatorFit} /><Factor label="Recurring" value={candidate.recurringRevenue} /><Factor label="Automation" value={candidate.automationPotential} /><div className="md:col-span-2"><Info label="Confidence" value={candidate.confidence} /></div></CardContent></Card>; }
function PipelineCard({ item }: { item: typeof opportunityPipeline[number] }) { return <Card className="border-cyan-300/25"><CardHeader><CardTitle className="text-lg">{item.opportunity}</CardTitle><CardDescription><StatusBadge label={item.stage} tone={stageTone[item.stage]} /></CardDescription></CardHeader><CardContent className="space-y-3"><Info label="Next gate" value={item.nextGate} /><Info label="Evidence required" value={item.evidenceRequired} /></CardContent></Card>; }
function ScoreCard({ score }: { score: typeof revenueScores[number] }) { const knownScore = typeof score.score === "number"; return <Card className="border-amber-300/25"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><BarChart3 className="h-5 w-5 text-amber-200" />{score.opportunity}</CardTitle><CardDescription>{score.note}</CardDescription></CardHeader><CardContent className="space-y-3"><div className="rounded-md border border-border/70 bg-background/50 p-3"><div className="mb-2 flex items-center justify-between text-xs uppercase tracking-[0.14em] text-muted-foreground"><span>Composite Score</span><span>{knownScore ? score.score : "Unknown"}</span></div><div className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-gradient-to-r from-amber-300 to-emerald-300" style={{ width: knownScore ? score.score + "%" : "0%" }} /></div></div><div className="grid gap-2 md:grid-cols-2"><Factor label="Demand" value={score.demand} /><Factor label="Margin" value={score.margin} /><Factor label="Competition" value={score.competition} /><Factor label="Recurring" value={score.recurring} /><Factor label="Operator Fit" value={score.operatorFit} /><Factor label="Automation" value={score.automationPotential} /></div></CardContent></Card>; }
function ExperimentCard({ item }: { item: typeof experimentTracker[number] }) { return <Card className="border-purple-300/25"><CardHeader><CardTitle className="text-lg">{item.hypothesis}</CardTitle><CardDescription>{item.owner}</CardDescription></CardHeader><CardContent className="space-y-3"><Info label="Evidence" value={item.evidence} /><Info label="Decision" value={item.decision} /><Info label="Result" value={item.result} /></CardContent></Card>; }
function MetricCard({ label, value, note }: { label: string; value: string; note: string }) { return <Card className="border-blue-300/20"><CardHeader><CardTitle className="text-lg">{value}</CardTitle><CardDescription>{label}</CardDescription></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">{note}</p></CardContent></Card>; }
function WinCard({ win }: { win: typeof hallOfWins[number] }) { return <Card className="border-amber-300/20"><CardHeader className="flex-row items-start gap-3"><Trophy className="mt-1 h-5 w-5 text-amber-200" /><div><CardTitle className="text-lg">{win.milestone}</CardTitle><CardDescription>{win.evidence}</CardDescription></div><StatusBadge label={win.status} tone="muted" /></CardHeader></Card>; }
function RadarCard({ item }: { item: typeof opportunityRadar[number] }) { return <Card className="border-cyan-300/20"><CardHeader className="flex-row items-start gap-3"><Radar className="mt-1 h-5 w-5 text-cyan-200" /><div><CardTitle className="text-lg">{item.opportunity}</CardTitle><CardDescription>{item.platform}</CardDescription></div><StatusBadge label={item.status} tone={radarTone[item.status]} /></CardHeader></Card>; }
function PlaybookCard({ entry }: { entry: typeof playbookLibrary[number] }) { return <Card className="border-emerald-300/20"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><FileText className="h-5 w-5 text-emerald-200" />{entry.title}</CardTitle><CardDescription>{entry.status}</CardDescription></CardHeader><CardContent className="space-y-3"><Info label="Workflow" value={entry.workflow} /><Info label="Evidence" value={entry.evidence} /></CardContent></Card>; }
function SenateCard({ item }: { item: typeof senateRecommendations[number] }) { return <Card className="border-fuchsia-300/25"><CardHeader><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-md border border-fuchsia-300/30 bg-fuchsia-300/10 text-2xl">{item.emoji}</span><div><CardTitle className="text-lg">{item.advisor}</CardTitle><CardDescription>{item.domain}</CardDescription></div></div><StatusBadge label={item.confidence} tone={confidenceTone[item.confidence]} /></div></CardHeader><CardContent className="space-y-3"><Info label="Recommendation" value={item.recommendation} /><Info label="Evidence" value={item.evidence} /></CardContent></Card>; }
